2014/09/02 14:45:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in E:\xampp\htdocs\learngit\framework\db\CDbConnection.php:382
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 E:\xampp\htdocs\learngit\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\learngit\framework\base\CModule.php(387): CDbConnection->init()
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1517): CActiveRecord->getTableAlias(true)
#7 E:\xampp\htdocs\learngit\protected\components\UserIdentity.php(40): CActiveRecord->findByAttributes(Array)
#8 E:\xampp\htdocs\learngit\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#9 E:\xampp\htdocs\learngit\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 E:\xampp\htdocs\learngit\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 E:\xampp\htdocs\learngit\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 E:\xampp\htdocs\learngit\protected\controllers\SiteController.php(95): CModel->validate()
#13 E:\xampp\htdocs\learngit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 E:\xampp\htdocs\learngit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#21 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('login')
#23 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#24 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/learngit/index.php/site/login
HTTP_REFERER=http://localhost/learngit/index.php/site/login
---
2014/09/03 07:54:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:58:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:59:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:01:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:01:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 09:10:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:10:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:10:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:10:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:11:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:11:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:12:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:12:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/04 19:38:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/04 19:38:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/04 19:38:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/04 19:38:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/05 12:39:22 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:04:09 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:04:10 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:04:11 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:05:29 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:05:52 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:06:05 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
---
2014/09/05 13:08:06 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:09:23 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:12:58 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:13:05 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:13:12 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 13:14:23 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 15:22:01 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/und...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/undefined
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 15:22:05 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/und...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/undefined
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 15:30:46 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/und...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/undefined
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/05 15:34:13 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/30/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/30/29
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/30
---
2014/09/05 15:34:22 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/30/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/30/29/28/29
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/30
---
2014/09/05 15:34:48 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/29/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/29/27
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/29
---
2014/09/05 15:34:52 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/29/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/29/27
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/29
---
2014/09/05 15:34:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/29/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/29/27
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/29
---
2014/09/05 15:36:38 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound. The SQL statement executed was: select * from file_relation inner join file on file_relation.file_id=file.file_id where user_id=1 and file.file_id=27?id=23.
in E:\xampp\htdocs\learngit\protected\controllers\SiteController.php (340)
in E:\xampp\htdocs\learngit\index.php (13)
2014/09/05 15:36:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound. The SQL statement executed was: select * from file_relation inner join file on file_relation.file_id=file.file_id where user_id=1 and file.file_id=27?id=23' in E:\xampp\htdocs\learngit\framework\db\CDbCommand.php:543
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1558): CDbCommand->queryRow()
#2 E:\xampp\htdocs\learngit\protected\controllers\SiteController.php(340): CActiveRecord->findBySql('select * from f...')
#3 [internal function]: SiteController->actionDelete('27?id=23')
#4 E:\xampp\htdocs\learngit\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#5 E:\xampp\htdocs\learngit\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#13 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#15 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#16 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/learngit/index.php/site/delete?id=27?id=23
HTTP_REFERER=http://localhost/learngit/index.php/site/delete?id=27
---
2014/09/05 15:52:31 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/1/2...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/1/25
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/1
---
2014/09/05 15:52:43 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/28/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/28/26
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/28
---
2014/09/05 15:52:47 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/28/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/28/26
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/28
---
2014/09/05 15:52:51 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/28/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/28/11
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/28
---
2014/09/05 16:00:13 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/
---
2014/09/05 16:01:24 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/12/...')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/12/3
HTTP_REFERER=http://localhost/learngit/index.php/site/delete/12
---
2014/09/05 16:07:01 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in E:\xampp\htdocs\learngit\framework\web\CController.php:336
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#7 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('delete')
#9 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/delete/3/9')
#10 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/learngit/index.php/site/delete/3/9
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/08 08:07:37 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id in (select file_id from file_relation where type=1 and locate=(select locate ' at line 1. The SQL statement executed was: select * from folder where folder id in (select file_id from file_relation where type=1 and locate=(select locate from file_relation where file_relation_id=19)).
in E:\xampp\htdocs\learngit\protected\controllers\SiteController.php (433)
in E:\xampp\htdocs\learngit\index.php (13)
2014/09/08 08:07:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id in (select file_id from file_relation where type=1 and locate=(select locate ' at line 1. The SQL statement executed was: select * from folder where folder id in (select file_id from file_relation where type=1 and locate=(select locate from file_relation where file_relation_id=19))' in E:\xampp\htdocs\learngit\framework\db\CDbCommand.php:543
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1581): CDbCommand->queryAll()
#2 E:\xampp\htdocs\learngit\protected\controllers\SiteController.php(433): CActiveRecord->findAllBySql('select * from f...')
#3 [internal function]: SiteController->actionMove('19')
#4 E:\xampp\htdocs\learngit\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#5 E:\xampp\htdocs\learngit\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#13 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('move')
#15 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/move')
#16 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/learngit/index.php/site/move/19
HTTP_REFERER=http://localhost/learngit/index.php
---
2014/09/08 08:07:44 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id in (select file_id from file_relation where type=1 and locate=(select locate ' at line 1. The SQL statement executed was: select * from folder where folder id in (select file_id from file_relation where type=1 and locate=(select locate from file_relation where file_relation_id=19)).
in E:\xampp\htdocs\learngit\protected\controllers\SiteController.php (433)
in E:\xampp\htdocs\learngit\index.php (13)
2014/09/08 08:07:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id in (select file_id from file_relation where type=1 and locate=(select locate ' at line 1. The SQL statement executed was: select * from folder where folder id in (select file_id from file_relation where type=1 and locate=(select locate from file_relation where file_relation_id=19))' in E:\xampp\htdocs\learngit\framework\db\CDbCommand.php:543
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1581): CDbCommand->queryAll()
#2 E:\xampp\htdocs\learngit\protected\controllers\SiteController.php(433): CActiveRecord->findAllBySql('select * from f...')
#3 [internal function]: SiteController->actionMove('19')
#4 E:\xampp\htdocs\learngit\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#5 E:\xampp\htdocs\learngit\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#13 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('move')
#15 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/move')
#16 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/learngit/index.php/site/move/19
HTTP_REFERER=http://localhost/learngit/index.php
---
