2014/09/02 14:45:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in E:\xampp\htdocs\learngit\framework\db\CDbConnection.php:382
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 E:\xampp\htdocs\learngit\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\learngit\framework\base\CModule.php(387): CDbConnection->init()
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 E:\xampp\htdocs\learngit\framework\db\ar\CActiveRecord.php(1517): CActiveRecord->getTableAlias(true)
#7 E:\xampp\htdocs\learngit\protected\components\UserIdentity.php(40): CActiveRecord->findByAttributes(Array)
#8 E:\xampp\htdocs\learngit\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#9 E:\xampp\htdocs\learngit\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 E:\xampp\htdocs\learngit\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 E:\xampp\htdocs\learngit\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 E:\xampp\htdocs\learngit\protected\controllers\SiteController.php(95): CModel->validate()
#13 E:\xampp\htdocs\learngit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 E:\xampp\htdocs\learngit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#21 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('login')
#23 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#24 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/learngit/index.php/site/login
HTTP_REFERER=http://localhost/learngit/index.php/site/login
---
2014/09/03 07:54:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/yuan.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/yuan.png')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/yuan.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:58:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 07:59:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:00:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:01:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 08:01:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/arrow-r.png".' in E:\xampp\htdocs\learngit\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('images/arrow-r....')
#1 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/learngit/index.php/images/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/homePage
---
2014/09/03 09:10:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:10:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:10:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:10:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:11:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:11:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-d.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:12:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/03 09:12:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "undefinedimages".' in E:\xampp\htdocs\learngit\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\CController.php(270): CController->missingAction('undefinedimages')
#1 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('undefinedimages')
#2 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/undefinedi...')
#3 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/learngit/index.php/site/undefinedimages/arrow-r.png
HTTP_REFERER=http://localhost/learngit/index.php/site/classifyDoc
---
2014/09/04 19:38:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/04 19:38:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/04 19:38:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
2014/09/04 19:38:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\learngit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\learngit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\learngit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\learngit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\learngit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\learngit\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\learngit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(282): CController->run('logout')
#8 E:\xampp\htdocs\learngit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 E:\xampp\htdocs\learngit\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\learngit\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/learngit/index.php/site/logout
HTTP_REFERER=http://localhost/learngit/index.php/site/set
---
